'use client';
import {useEffect,useMemo,useState} from 'react';
import {LayoutDashboard, Search, FlaskConical, Users, ChartNoAxesCombined, ShieldCheck, ScrollText, ArrowUpRight, Shield, CheckCircle2, AlertTriangle, Activity, Database, BrainCircuit, Clock3, Download, Trash2, RotateCcw, ChevronRight, Info, ExternalLink, LockKeyhole} from 'lucide-react';
import {type CaseInput,type Assessment,SAMPLE_CASES,POLICY_VERSION} from '@/lib/risk';

type Page='Overview'|'Investigate'|'Custom Case Lab'|'Human Review'|'Model Benchmark'|'Governance'|'Audit Trail';
type SavedCase={assessment:Assessment;created_at:string;updated_at:string;status:'PENDING_REVIEW'|'AUTONOMOUS'|'ESCALATED'|'VERIFICATION_REQUIRED'|'REVIEW_RECORDED'|'FAIL_SAFE';investigator:string;rationale:string;decision:string};
type Log={at:string;case_id:string;event:string;detail:string};
const NAV: {label:Page;icon:React.ComponentType<{size?:number;strokeWidth?:number}>}[]=[
  {label:'Overview',icon:LayoutDashboard},{label:'Investigate',icon:Search},
  {label:'Custom Case Lab',icon:FlaskConical},{label:'Human Review',icon:Users},
  {label:'Model Benchmark',icon:ChartNoAxesCombined},{label:'Governance',icon:ShieldCheck},
  {label:'Audit Trail',icon:ScrollText}
];
const STORE='aegis2-vercel-local-demo-v1';
const HIGH:CaseInput={customer_name:'Custom Test Customer',home_city:'Pune',average_transaction:6500,amount:175000,transaction_time:'02:13',location:'Singapore',device_id:'ANDROID-X91',device_status:'New',beneficiary_status:'New',failed_auth_attempts:5,usual_start_hour:8,usual_end_hour:22,channel:'Mobile Banking',merchant_category:'Bank Transfer',alert_reason:'Unusual high-value transfer'};
const BENCH=[
  {name:'Qwen3.8 27B',accuracy:66.67,escalation:66.67,hallucination:66.67,structured:66.67,completion:66.67,explanation:'3.33 / 5',latency:'9,994 ms'},
  {name:'Nemotron 3.5 Lightning',accuracy:33.33,escalation:33.33,hallucination:33.33,structured:66.67,completion:66.67,explanation:'3.00 / 5',latency:'4,892 ms'},
  {name:'Gemma 4 31B',accuracy:100,escalation:100,hallucination:100,structured:100,completion:100,explanation:'5.00 / 5',latency:'5,675 ms'}
];
const fmtMoney=(x:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(x);
const fmtDate=(s:string)=>new Date(s).toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'});
const riskStyle=(risk:string)=>risk==='HIGH'||risk==='UNKNOWN'?'danger':risk==='MEDIUM'?'amber':'success';
const getSaved=():{cases:SavedCase[];logs:Log[]}=>{try{const x=JSON.parse(localStorage.getItem(STORE)||'{}');return {cases:Array.isArray(x.cases)?x.cases:[],logs:Array.isArray(x.logs)?x.logs:[]}}catch{return {cases:[],logs:[]}}};
function Chip({children,tone='neutral'}:{children:React.ReactNode;tone?:string}){return <span className={`chip ${tone}`}>{children}</span>}
function Stat({title,value,sub}:{title:string;value:string|number;sub?:string}){return <div className="stat"><span>{title}</span><strong>{value}</strong>{sub&&<small>{sub}</small>}</div>}
function Panel({title,kicker,children}:{title:string;kicker?:string;children:React.ReactNode}){return <section className="panel"><header className="panel-head"><div>{kicker&&<div className="eyebrow">{kicker}</div>}<h3>{title}</h3></div></header>{children}</section>}
function Field({title,children}:{title:string;children:React.ReactNode}){return <label className="field"><span>{title}</span>{children}</label>}
const passBadge=(assessment:Assessment)=><Chip tone={riskStyle(assessment.risk_level)}>{assessment.risk_level}</Chip>;
export default function Dashboard(){
  const [page,setPage]=useState<Page>('Overview');
  const [cases,setCases]=useState<SavedCase[]>([]);const [logs,setLogs]=useState<Log[]>([]);
  const [ready,setReady]=useState(false);const [form,setForm]=useState<CaseInput>(HIGH);
  const [last,setLast]=useState<Assessment|null>(null);const [isLoading,setLoading]=useState(false);
  const [error,setError]=useState('');const [selected,setSelected]=useState('');
  const [name,setName]=useState('Human Fraud Investigator');const [decision,setDecision]=useState('ESCALATE TO SENIOR INVESTIGATOR');const [rationale,setRationale]=useState('');
  const [resultTab,setResultTab]=useState<'Risk Signals'|'Evidence Gate'|'Specialist Views'>('Risk Signals');
  useEffect(()=>{const x=getSaved();setCases(x.cases);setLogs(x.logs);setReady(true)},[]);
  useEffect(()=>{if(ready)localStorage.setItem(STORE,JSON.stringify({cases,logs}))},[cases,logs,ready]);
  const pending=cases.filter(c=>c.status==='PENDING_REVIEW'||c.status==='FAIL_SAFE'||c.status==='VERIFICATION_REQUIRED');
  const activeCase=cases.find(c=>c.assessment.case_id===selected)||cases[0];
  const addLog=(case_id:string,event:string,detail:string)=>setLogs(old=>[{at:new Date().toISOString(),case_id,event,detail},...old].slice(0,300));
  const setField=(key:keyof CaseInput,value:string|number)=>setForm(old=>({...old,[key]:value}));
  const loadSample=(i:number)=>{const {case_id:_id,...fields}=SAMPLE_CASES[i];setForm(fields);setPage('Custom Case Lab');setLast(null);setError('')};
  async function investigate(){
    setLoading(true);setError('');
    try{
      const response=await fetch('/api/investigate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});
      if(!response.ok)throw new Error(`Risk service returned ${response.status}`);
      const result=await response.json() as {assessment:Assessment};
      const a=result.assessment;setLast(a);setResultTab('Risk Signals');
      const status:SavedCase['status']=a.risk_level==='LOW'?'AUTONOMOUS':a.risk_level==='UNKNOWN'?'FAIL_SAFE':'PENDING_REVIEW';
      const now=new Date().toISOString();
      const record:SavedCase={assessment:a,created_at:now,updated_at:now,status,investigator:'UNASSIGNED',rationale:'',decision:''};
      setCases(old=>[record,...old].slice(0,200));addLog(a.case_id,'GOVERNED_RISK_EVALUATED',`${a.risk_level} · ${a.risk_score===null?'NOT SCORED':a.risk_score+'/100'} · ${a.recommended_action}`);
      setSelected(a.case_id);
    }catch(e){setError(e instanceof Error?e.message:'Investigation failed safely')}
    finally{setLoading(false)}
  }
  function recordReview(){
    if(!activeCase||!name.trim()||rationale.trim().length<12){setError('Add an investigator name and rationale of at least 12 characters.');return}
    if(activeCase.assessment.risk_level==='HIGH'&&decision==='PROCEED'){setError('Policy blocks direct PROCEED for HIGH-risk cases.');return}
    const now=new Date().toISOString();
    setCases(old=>old.map(c=>c.assessment.case_id===activeCase.assessment.case_id?{...c,updated_at:now,investigator:name.trim(),decision,rationale:rationale.trim(),status:decision==='ESCALATE TO SENIOR INVESTIGATOR'?'ESCALATED':decision==='VERIFY CUSTOMER'?'VERIFICATION_REQUIRED':'REVIEW_RECORDED'}:c));
    addLog(activeCase.assessment.case_id,'BROWSER_ONLY_HUMAN_NOTE',`${name}: ${decision}. ${rationale.trim()}`);
    setRationale('');setError('');
  }
  function resetLocal(){if(!confirm('Clear only this browser’s demonstration cases and event history?'))return;setCases([]);setLogs([]);setSelected('');setLast(null)}
  function exportLog(){const blob=new Blob([JSON.stringify({source:'BROWSER-ONLY-DEMONSTRATION',cases,logs},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='aegis-browser-demo-audit.json';a.click();URL.revokeObjectURL(url)}
  const caseCount=useMemo(()=>cases.length,[cases]);
  const highCount=cases.filter(c=>c.assessment.risk_level==='HIGH').length;
  return <div className="shell">
    <aside className="sidebar">
      <a className="brand" href="/portfolio.html"><span className="brand-icon">A</span><span><strong>AEGIS</strong><small>FRAUD INTELLIGENCE</small></span></a>
      <div className="sidebar-label">COMMAND CENTER</div>
      <nav aria-label="AEGIS pages">{NAV.map((item,i)=>{const Icon=item.icon;return <button type="button" onClick={()=>{setPage(item.label);setError('')}} key={item.label} className={`nav-item ${page===item.label?'active':''}`}><Icon size={17}/><span>{String(i+1).padStart(2,'0')} {item.label}</span>{item.label==='Human Review'&&pending.length>0&&<b className="nav-counter">{pending.length}</b>}</button>})}</nav>
      <div className="sidebar-bottom"><div className="operation"><span className="on-dot"/> DEMO OPERATIONAL</div><div className="sb-line"><span>ENVIRONMENT</span><b>SYNTHETIC</b></div><div className="sb-line"><span>RISK ENGINE</span><b>POLICY 2.0</b></div><div className="sb-line"><span>N8N</span><b>NOT CONNECTED</b></div><div className="sb-line"><span>CASE STORAGE</span><b>THIS BROWSER</b></div></div>
      <a className="sidebar-link" href="/portfolio.html"><ArrowUpRight size={14}/> Return to Portfolio</a>
    </aside>
    <main className="content">
      <div className="topbar"><div className="breadcrumb">AEGIS / <strong>{page.toUpperCase()}</strong></div><div className="topstatus"><span className="on-dot"/> VERCEL DEMONSTRATOR <span className="div-dot">•</span> NO BANKING ACTIONS</div></div>
      <div className="pagebody">
      {page==='Overview'&&<>
        <header className="page-head"><div className="eyebrow">AEGIS / GOVERNED FRAUD INVESTIGATION</div><h1>Fraud intelligence.<br/><em>Human authority.</em></h1><p>Evidence-driven fraud assessment using the original AEGIS deterministic risk scoring policy, adapted for Vercel.</p></header>
        <div className="notice"><Info size={18}/><span><b>Hosted demonstration:</b> This version computes real rule-based risk scores. AI model calls, n8n callbacks and shared durable storage are not connected. Investigator notes are saved only in your current browser.</span></div>
        <div className="stats"><Stat title="Local Cases" value={caseCount} sub="This browser only"/><Stat title="Awaiting Review" value={pending.length}/><Stat title="High Risk" value={highCount}/><Stat title="Governance" value="ACTIVE" sub={POLICY_VERSION}/></div>
        <div className="two-cols"><Panel title="Run an investigation" kicker="Start here"><p className="muted">Choose a case profile to run the same deterministic risk rules as the original Python proof of concept.</p><div className="preset-list"><button onClick={()=>loadSample(0)}><Chip tone="success">LOW</Chip><span>Normal transaction</span><b>₹4,200</b><ChevronRight size={16}/></button><button onClick={()=>loadSample(1)}><Chip tone="amber">MEDIUM</Chip><span>Domestic anomaly</span><b>₹48,000</b><ChevronRight size={16}/></button><button onClick={()=>loadSample(2)}><Chip tone="danger">HIGH</Chip><span>Foreign transfer</span><b>₹1,75,000</b><ChevronRight size={16}/></button></div></Panel><Panel title="Authority boundary" kicker="Security posture"><div className="principles"><div><BrainCircuit/><strong>AI analyses.</strong><span>Specialist roles are explained but live LLM inference is not connected in this hosted demo.</span></div><div><ShieldCheck/><strong>Policy governs.</strong><span>Thresholds and signals are applied deterministically on the server.</span></div><div><LockKeyhole/><strong>Human decides.</strong><span>Reviewer notes are illustrative, not authoritative bank approvals.</span></div></div></Panel></div>
        <Panel title="Recent browser activity" kicker="Local audit preview">{logs.length?<div className="timeline">{logs.slice(0,5).map((l,i)=><div key={i}><time>{fmtDate(l.at)}</time><strong>{l.event}</strong><span>{l.case_id} · {l.detail}</span></div>)}</div>:<p className="empty">No cases recorded in this browser yet. Launch an investigation to begin.</p>}</Panel>
      </>}
      {page==='Investigate'&&<>
        <header className="page-head"><div className="eyebrow">02 / INVESTIGATE</div><h1>Three cases.<br/><em>Three governed outcomes.</em></h1><p>Reference cases reconstructed from the original synthetic banking dataset.</p></header>
        <div className="case-card-grid">{SAMPLE_CASES.map((c,i)=><article className="sample-card" key={i}><div className="card-line"><Chip tone={i===0?'success':i===1?'amber':'danger'}>CASE 00{i+1}</Chip><span>{c.location}</span></div><h2>{fmtMoney(c.amount)}</h2><p>{c.customer_name}</p><div className="sample-stats"><span>Customer average <b>{fmtMoney(c.average_transaction)}</b></span><span>Device <b>{c.device_status}</b></span><span>Auth failures <b>{c.failed_auth_attempts}</b></span></div><button className="primary" onClick={()=>loadSample(i)}>Inspect and run <ArrowUpRight size={17}/></button></article>)}</div>
        <Panel title="Why this matters" kicker="Investigation ≠ detection"><p className="muted">A fraud alert is not proof of fraud. AEGIS assesses multiple signals and routes the case under deterministic policy. A real final decision requires verified human and banking-system integration, outside this hosted demonstrator.</p></Panel>
      </>}
      {page==='Custom Case Lab'&&<>
        <header className="page-head"><div className="eyebrow">03 / CUSTOM CASE LAB</div><h1>Case intake.<br/><em>Governed analysis.</em></h1><p>Enter synthetic transaction evidence, run a genuine risk assessment API, and inspect the contributing signals.</p></header>
        <div className="notice"><Info size={18}/><span>Use synthetic information only. This demonstration never contacts a bank or changes real transaction state.</span></div>
        <div className="preset-bar"><span>Load a reference scenario:</span>{SAMPLE_CASES.map((c,i)=><button key={i} className="pill-btn" onClick={()=>loadSample(i)}>{['Normal / LOW','Domestic / MEDIUM','Foreign / HIGH'][i]}</button>)}</div>
        <Panel title="Manual investigation intake" kicker="Evidence gathering"><form onSubmit={e=>{e.preventDefault();investigate()}}>
          <div className="form-section">Customer context</div><div className="form-grid"><Field title="Customer name"><input value={form.customer_name} onChange={e=>setField('customer_name',e.target.value)}/></Field><Field title="Home city"><input value={form.home_city} onChange={e=>setField('home_city',e.target.value)}/></Field><Field title="Historical average (₹)"><input type="number" min="0" value={form.average_transaction} onChange={e=>setField('average_transaction',Number(e.target.value))}/></Field><Field title="Alert reason"><input value={form.alert_reason||''} onChange={e=>setField('alert_reason',e.target.value)}/></Field></div>
          <div className="form-section">Transaction evidence</div><div className="form-grid"><Field title="Transaction amount (₹)"><input type="number" min="0" value={form.amount} onChange={e=>setField('amount',Number(e.target.value))}/></Field><Field title="Transaction time (HH:MM)"><input value={form.transaction_time} onChange={e=>setField('transaction_time',e.target.value)} placeholder="02:13"/></Field><Field title="Transaction location"><input value={form.location} onChange={e=>setField('location',e.target.value)}/></Field><Field title="Current device ID"><input value={form.device_id} onChange={e=>setField('device_id',e.target.value)}/></Field><Field title="Device status"><select value={form.device_status} onChange={e=>setField('device_status',e.target.value)}><option>Known</option><option>New</option></select></Field><Field title="Beneficiary status"><select value={form.beneficiary_status} onChange={e=>setField('beneficiary_status',e.target.value)}><option>Existing</option><option>New</option></select></Field><Field title="Authentication failures"><input type="number" min="0" value={form.failed_auth_attempts} onChange={e=>setField('failed_auth_attempts',Number(e.target.value))}/></Field><Field title="Channel"><input value={form.channel||''} onChange={e=>setField('channel',e.target.value)}/></Field><Field title="Usual start hour (0–23)"><input type="number" min="0" max="23" value={form.usual_start_hour} onChange={e=>setField('usual_start_hour',Number(e.target.value))}/></Field><Field title="Usual end hour (0–23)"><input type="number" min="0" max="23" value={form.usual_end_hour} onChange={e=>setField('usual_end_hour',Number(e.target.value))}/></Field></div>
          <div className="form-footer"><span className="muted">Policy {POLICY_VERSION} · Deterministic · No model inference</span><button className="primary" disabled={isLoading} type="submit">{isLoading?'Analyzing case...':'Run Governed Investigation'} <ArrowUpRight size={17}/></button></div>
        </form></Panel>
        {error&&<div className="notice error"><AlertTriangle size={18}/>{error}</div>}
        {last&&<><div className="result-hero"><div><div className="eyebrow">NEW CASE / {last.case_id}</div><h2>Governance decision</h2><div className="result-badges">{passBadge(last)}<Chip tone="neutral">{last.evidence_gate_status}</Chip><Chip>{last.recommended_action}</Chip></div></div><div className="risk-value"><span>RISK SCORE</span><strong>{last.risk_score===null?'N/A':last.risk_score}<small>{last.risk_score===null?'':' / 100'}</small></strong></div></div>
          <div className="stats"><Stat title="Governance action" value={last.recommended_action}/><Stat title="Human review" value={last.human_review?'REQUIRED':'NOT REQUIRED'}/><Stat title="Amount ratio" value={last.amount_ratio===null?'—':last.amount_ratio.toFixed(2)+'×'}/><Stat title="Banking action executed" value="NO"/></div>
          <div className="tabbar">{(['Risk Signals','Evidence Gate','Specialist Views'] as const).map(t=><button key={t} className={resultTab===t?'chosen':''} onClick={()=>setResultTab(t)}>{t}</button>)}</div>
          {resultTab==='Risk Signals'&&<Panel title={last.governance_route} kicker="Authoritative deterministic result"><div className="signal-grid">{last.signals.length?last.signals.map((s,i)=><div className="signal" key={i}><strong>+{s.points} pts</strong><div>{s.name}</div><small>{s.evidence}</small></div>):<p className="empty">No anomalous risk signals detected.</p>}</div></Panel>}
          {resultTab==='Evidence Gate'&&<Panel title="Evidence quality assessment" kicker="Fail-safe first"><div className="detail-grid"><span>Gate outcome <b>{last.evidence_gate_status}</b></span><span>Risk scored? <b>{last.risk_score_valid?'YES':'NO'}</b></span><span>Reason for fail-safe <b>{last.validation_issues.length?last.validation_issues.join('; '):'None'}</b></span><span>Policy version <b>{last.policy_version}</b></span></div></Panel>}
          {resultTab==='Specialist Views'&&<Panel title="Four specialist roles" kicker="Explanatory summaries · No live LLM"><div className="agent-grid">{[
            ['Transaction Intelligence',`This transfer of ${fmtMoney(last.input.amount)} is ${last.amount_ratio?.toFixed(1)??'N/A'}× the recorded customer average.`],
            ['Customer Behaviour',`Geography: ${last.input.home_city} → ${last.input.location}. Device: ${last.input.device_status}. Beneficiary: ${last.input.beneficiary_status}.`],
            ['Policy & Risk',`The deterministic policy classified this case as ${last.risk_level}; route: ${last.governance_route}.`],
            ['Recommendation',`Governed next step: ${last.recommended_action}. This descriptive panel is not a language-model inference.`]
          ].map(([title,detail],i)=><div className="agent" key={title}><div className="eyebrow">AGENT ROLE 0{i+1}</div><h4>{title}</h4><p>{detail}</p><small>Deterministic explanatory view</small></div>)}</div></Panel>}
          <div className="notice warn"><Info size={18}/><span>Local case record created. This hosted deployment has <b>not</b> sent the case to n8n or a real LLM. Select <button className="inline-action" onClick={()=>setPage('Human Review')}>Human Review</button> to record an illustrative analyst note.</span></div>
        </>}
      </>}
      {page==='Human Review'&&<>
        <header className="page-head"><div className="eyebrow">04 / HUMAN REVIEW</div><h1>Human authority.<br/><em>Clear accountability.</em></h1><p>Review browser-local synthetic cases and capture illustrative investigator notes.</p></header>
        <div className="notice warn"><AlertTriangle size={18}/><span><strong>This is NOT the original n8n Human-in-the-Loop workflow.</strong> Notes saved here stay in this browser; no callback or final audit sync occurs.</span></div>
        <div className="stats"><Stat title="Cases in this browser" value={cases.length}/><Stat title="Awaiting local review" value={pending.length}/><Stat title="Local escalations" value={cases.filter(x=>x.status==='ESCALATED').length}/><Stat title="Missing server persistence" value="YES"/></div>
        {cases.length?<div className="two-cols human-cols"><Panel title="Investigation queue" kicker="Browser-local"><div className="queue-list">{cases.map(c=><button key={c.assessment.case_id} onClick={()=>{setSelected(c.assessment.case_id);setError('')}} className={`queue-row ${activeCase?.assessment.case_id===c.assessment.case_id?'selected':''}`}><span><b>{c.assessment.case_id}</b><small>{c.assessment.input.customer_name}</small></span>{passBadge(c.assessment)}<small>{c.status}</small></button>)}</div></Panel><Panel title="Investigator review" kicker="Not a banking action">{activeCase&&<><div className="review-summary"><div>Selected case <b>{activeCase.assessment.case_id}</b></div><div>Risk class {passBadge(activeCase.assessment)}</div><div>Risk score <b>{activeCase.assessment.risk_score===null?'NOT SCORED':activeCase.assessment.risk_score}</b></div><div>Governance action <b>{activeCase.assessment.recommended_action}</b></div><div>Queue status <b>{activeCase.status}</b></div></div><Field title="Investigator name"><input value={name} onChange={e=>setName(e.target.value)}/></Field><Field title="Illustrative review note"><select value={decision} onChange={e=>setDecision(e.target.value)}><option>ESCALATE TO SENIOR INVESTIGATOR</option><option>HOLD AND REVIEW</option><option>VERIFY CUSTOMER</option></select></Field><Field title="Evidence-based rationale"><textarea value={rationale} onChange={e=>setRationale(e.target.value)} placeholder="Record the rationale supporting the review..." rows={5}/></Field><button className="primary wide" onClick={recordReview}>Save Browser-Only Investigator Note <ArrowUpRight size={17}/></button>{activeCase.decision&&<div className="saved-note"><CheckCircle2 size={16}/> Last local note: {activeCase.decision} by {activeCase.investigator}<p>{activeCase.rationale}</p></div>}</>}</Panel></div>:<Panel title="No investigations yet"><p className="empty">Open Custom Case Lab and run a synthetic transaction first.</p><button className="primary" onClick={()=>setPage('Custom Case Lab')}>Create case <ChevronRight size={15}/></button></Panel>}
        {error&&<div className="notice error"><AlertTriangle size={18}/>{error}</div>}
      </>}
      {page==='Model Benchmark'&&<><header className="page-head"><div className="eyebrow">05 / OPEN-MODEL COMPARISON</div><h1>Three models.<br/><em>Controlled comparison.</em></h1><p>Results transcribed from the original project's recorded three-case benchmark.</p></header><div className="notice warn"><Info size={18}/><span>These results are <b>historical, not live Vercel executions</b>. Three cases per model cannot establish production-grade accuracy.</span></div><div className="model-grid">{BENCH.map((b,i)=><Panel key={b.name} title={b.name} kicker={`MODEL 0${i+1}`}><div className="model-big">{b.accuracy.toFixed(2)}<small>%</small></div><div className="metric-name">Classification quality</div>{([['Escalation',b.escalation],['Hallucination-free',b.hallucination],['Structured Output',b.structured],['Task Completion',b.completion]] as [string,number][]).map(([name,n])=><div className="bar-metric" key={name}><div><span>{name}</span><b>{n.toFixed(2)}%</b></div><div className="bar-track"><i style={{width:n+'%'}}/></div></div>)}<div className="bench-footer"><div>Explanation <b>{b.explanation}</b></div><div>Avg. Latency <b>{b.latency}</b></div><div>Test cases <b>3</b></div></div></Panel>)}</div></>}
      {page==='Governance'&&<><header className="page-head"><div className="eyebrow">06 / DETERMINISTIC GOVERNANCE</div><h1>Policy owns<br/><em>the route.</em></h1><p>The LLM is never the final authority for financial decisions in the original AEGIS design.</p></header><div className="route-grid">{[{risk:'LOW',tag:'AUTONOMOUS',action:'PROCEED',description:'No human review required by the prototype governance policy.'},{risk:'MEDIUM',tag:'HUMAN',action:'VERIFY CUSTOMER',description:'Explicit customer verification is required before progression.'},{risk:'HIGH',tag:'ESCALATION',action:'HOLD AND REVIEW',description:'Human investigation and possible senior escalation required.'},{risk:'UNKNOWN',tag:'FAIL SAFE',action:'MANUAL REVIEW',description:'Missing or invalid critical evidence blocks risk scoring.'}].map(r=><div className="route-card" key={r.risk}>{<Chip tone={riskStyle(r.risk)}>{r.risk} / {r.tag}</Chip>}<h2>{r.action}</h2><p>{r.description}</p></div>)}</div><Panel title="Guardrail inventory" kicker="Prototype scope"><div className="guard-rows"><div><strong>Deterministic score</strong><span>Risk points and routing are calculated without LLM authority.</span><Chip tone="success">IMPLEMENTED</Chip></div><div><strong>Missing evidence</strong><span>Fails safe to manual review, never silent LOW.</span><Chip tone="success">IMPLEMENTED</Chip></div><div><strong>Human decision</strong><span>Original local Python + n8n handles callbacks; hosted dashboard currently saves browser-only notes.</span><Chip tone="amber">HOSTING GAP</Chip></div><div><strong>Audit persistence</strong><span>Shared durable audit records require an external database/service.</span><Chip tone="amber">NOT HOSTED</Chip></div><div><strong>Irreversible actions</strong><span>No real payment approval, freeze or funds movement is performed.</span><Chip tone="success">DISABLED</Chip></div></div></Panel></>}
      {page==='Audit Trail'&&<><header className="page-head"><div className="eyebrow">07 / LOCAL TRACE</div><h1>Every decision.<br/><em>A visible trace.</em></h1><p>Browser-local activity history for this hosted demonstrator.</p></header><div className="notice"><Database size={18}/><span>Unlike the original Python append-only audit system, this record is <strong>editable/deletable browser storage</strong>. It is not a tamper-proof or shared audit ledger.</span></div><div className="tools-row"><button className="pill-btn" onClick={exportLog}><Download size={15}/> Export local JSON</button><button className="pill-btn danger-action" onClick={resetLocal}><Trash2 size={15}/> Clear browser demonstration</button><button className="pill-btn" onClick={()=>{setPage('Custom Case Lab');setForm(HIGH)}}><RotateCcw size={15}/> New case</button></div><Panel title="Case event timeline" kicker="Local-only">{logs.length?<div className="timeline detailed">{logs.map((l,i)=><div key={`${l.at}-${i}`}><time><Clock3 size={13}/>{fmtDate(l.at)}</time><strong>{l.event}</strong><span><b>{l.case_id}</b> · {l.detail}</span></div>)}</div>:<p className="empty">No local events have been recorded.</p>}</Panel></>}
      </div>
      <footer className="app-footer">AEGIS 2.0 / SYNTHETIC ACADEMIC PROTOTYPE <span>RULE-BASED RISK SERVICE · BROWSER-LOCAL REVIEW · NO LIVE N8N</span><a href="/portfolio.html">Project Portfolio <ExternalLink size={13}/></a></footer>
    </main>
  </div>
}
